'use strict';

export const stories = [
    {
        title: "Grandpa and the Banana Spider",
        content: [
            ["One day, while the kids—Angie, Tony, and Nuby—were playing in the backyard of our house in Florida, they saw a big spider web. And right in the middle of it was a really big <span class='accent'>banana spider!</span>"],
            ["Banana spider webs are huge, and sometimes they're even yellow in color. They don’t bite people, but the kids were still scared."],
            ["First, Daddy went to help and see how they could get rid of the banana spider. But Grandpa was a big softy when it came to spiders. He didn’t like killing them.", "\"I got an idea!\" Grandpa said with excitement. He went inside the house and came back out with an empty Pringles can."],
            ["\"I'll use this,\" he said with a grin. Grandpa carefully approached the spider with the open can. The kids watched, afraid from a distance."],
            ["<strong>SNAP!</strong> He got it!"],
            ["\"Okay, son,\" Grandpa told Daddy. \"Let’s go take it to the front of the neighborhood.\"", "Daddy drove Grandpa to the front of the neighborhood, with Grandpa sitting in the passenger seat, holding the spider in the can."],
            ["They arrived at a tree and a patch of grass. Grandpa got out of the car while Daddy waited."],
            ["Suddenly, Grandpa came running back to the car, his face pale. He jumped in and said, \"I didn’t see him! I opened the can, and I didn’t see him! Check my back! Check my back!\""],
            ["Grandpa was brave enough to capture the spider, but when he didn’t see him, he was just as scared as the kids!", "Daddy laughed and reassured him, \"Nothing on your back, Dad.\"", "And with that, they drove back home safely, leaving the banana spider in his new home."]
        ],
        bg_color: "#6bb4fd", 
        svg_variant: "1"
    },
    {
        title: "Grandpa Talks To Squirrels",
        content: [
            ["One day, when Daddy, Titi Sofi, and Titi Lali were little, it was Grandpa's turn to take care of them while Grandma went out. He said, \"Let's go to the park!\""],
            ["They were always excited when Grandpa took them out because they never knew what crazy things were going to happen with him while Grandma was away. So Grandpa packed some yummy peanut butter and jelly sandwiches, and they went to C. B. Smith Park."],
            ["After some time playing, we all decided to have our peanut butter and jelly sandwiches. When all of a sudden, a squirrel came down from a tree, to the closest tree branch he could find (without getting too close to us humans)."],
            ["The squirrel looked at Grandpa and started pointing both of his little hands into his little squirrel chest. It looked like he was asking Grandpa, 'Can I have some?' And Grandpa said, 'Do you want some? Sure, you can have a piece.' And he took a bit of the sandwich and left it on the table."],
            ["Mr. Squirrel came down from the tree, grabbed it, then went right up to his branch to eat it. We couldn't believe it! Did Grandpa and the squirrel know how to talk to each other?"],
            ["It sure looked like it! We tried to call him down, but he just ignored us. I think only Grandpa had squirrel powers."]
        ],
        bg_color: "#8053fa", 
        svg_variant: "1"
    },
    {
        title: "Grandpa Plays Zelda",
        content: [
            ["When we were little kids, we had the first Nintendo game system. It was called the NES! Our video games came in big rectangles called cartridges."],
            ["We had a lot of fun, and we thought the NES was just for us kids. But one day, Grandpa found one of our game cartridges called <strong>The Legend of Zelda</strong>. It came in a special gold cartridge."],
            ["Zelda was always hard for us to play, so we stuck to easier games like Mario and Duck Hunt."],
            ["But when Grandpa tried out Zelda, he loved it! Because Grandpa only had one hand, he bought a special controller called a joystick that he could use with his left arm while fighting the bad guys with his right hand."],
            ["Grandpa got really good at the game. There were so many secret doors in Zelda, and the only way to find them was by placing a bomb near a wall and seeing what happened."],
            ["If you found a secret door—BOOM!—it exploded, a special sound played, and you could find a hidden treasure!"],
            ["So Grandpa would always say, \"Put a bomb there!\" whenever someone was playing Zelda because he knew where to find the hiding places."],
            ["Our Zelda cartridge was great, but it had one problem—it didn’t save! So Grandpa had to keep the game on all night so he could pass it and save the princess."],
            ["Sometimes, we would wake up late to get water and find Grandpa still playing Zelda!"],
            ["Sometimes, we wanted to play, but Grandpa had to finish the game. And one day, he did!"],
            ["He defeated all of the castles, beat the bad guy, Ganon, got the Triforce trophy, and saved the princess."],
            ["The NES was made for kids, but Grandpa was the Zelda master."]
        ],
        bg_color: "#d92626", 
        svg_variant: "1"
    },
    {
        title: "Grandpa Helps Santa",
        content: [
            ["Grandpa helped a lot of people in a lot of different ways. One way he helped was through the Angel Tree program."],
            ["Every year, during Christmas time, Grandpa, Grandma, and all their friends from church would collect toys for little kids whose parents didn’t have enough, or kids who only had one mommy or daddy."],
            ["They would gather all of these toys in the living room of their old house in Florida. There were soooooo many toys!"],
            ["Daddy loved seeing all of those toys when he was little. He once asked Grandpa, \"Can I just have one toy?\""],
            ["But Grandpa would smile and say, \"Those are for little boys and girls who need them more than you.\" And he was right!"],
            ["Sometimes, when it was time to deliver gifts, Grandpa would let Daddy go with him."],
            ["Daddy got to see how happy the families were when they received a bag full of toys. It made Daddy feel happier than getting toys himself!"],
            ["Giving is better than receiving!"],
            ["Did you know St. Nicholas (or, as some people call him, Santa Claus) also gave gifts to people who needed help?"],
            ["Whenever we do that—especially in secret—we’re helping St. Nicholas, just like Grandpa!"]
        ],
        bg_color: "#32a658",
        svg_variant: "santa",
    }, 
    {
        title: "Grandpa's Car, Clunker",
        content: [
            ["When Daddy was little, Grandpa had a car he called \"Clunker.\""],
            ["He called it Clunker because every time the car was on, it would go \"clunk clunk clunk clunk.\""],
            ["Clunker had a lot of problems because it was an old car. But Grandpa loved projects—especially if the project was fixing broken things."],
            ["One of Clunker’s biggest problems was that it would overheat!"],
            ["The engine would get too, too hot. And when the engine gets too hot, it can be dangerous!"],
            ["One time, the car got so hot while Titi Sofi and Daddy were in it that Grandpa stopped the car, turned it off, and shouted, \"Get out! The car is gonna blow up!\""],
            ["Titi Sofi and Daddy weren’t scared, though, because Grandpa was always doing crazy things. We were used to it!"],
            ["Another time, Grandpa had to pick us up from school with Titi Lali, but he couldn’t stop the car!"],
            ["If he stopped the car, it would get too hot!"],
            ["So he picked us up, but he kept the car moving. When it was time for us to go home, he yelled from the window, \"Get inside! I can't stop!\""],
            ["Again, Titi Sofi and Daddy weren’t scared. We thought it was fun!"],
            ["Finally, Grandpa said, \"I’m going to fix this myself!\""],
            ["So he put a little fan inside the car that would help cool the engine down if it got too hot."],
            ["He even installed a switch inside the car to turn the fan on and off!"],
            ["And to make it even better, he added a light to let him know when the fan was on."],
            ["Grandpa was really smart... but he did do some crazy things!"],
            ["Later, we got a new car that always stayed cool, but we’ll always remember Grandpa’s crazy Clunker."]
        ],
        bg_color: "#bf8f68",
        svg_variant: "1",
    },
    {
        title: "Grandpa and the Giant Iguana",
        content: [
            ["In Florida, where we used to live, there were a lot of iguanas."],
            ["We had them in our neighborhood, we would see them on the side of the road, they would climb trees, and we even had them in our backyard!"],
            ["One day, when Grandpa and Daddy were cleaning up the backyard to get ready for Mommy and Daddy’s wedding, we saw the biggest iguana!"],
            ["It was maybe four feet long with its tail!"],
            ["We liked looking at it, but we knew he couldn’t stay in our backyard."],
            ["So we started to try and scare it so it would leave."],
            ["At first, it didn’t move. Then... it ran!"],
            ["I didn’t know iguanas could be so fast!"],
            ["It ran from the backyard to the front of the house."],
            ["And someone left the front door open!"],
            ["Aaaahhhhhhh! The iguana got inside the house!!"],
            ["Grandpa went in from the backyard door and met him inside."],
            ["I don’t know what he did, but the iguana came running back out through the front door!"],
            ["I guess the iguana knew who was the boss of the house."],
            ["He left safely and probably found another backyard and some shade to rest under."]
        ],
        bg_color: "#ef6c01",
        svg_variant: "1",
    },
    {
        title: "Grandpa's Pep Shake",
        content: [
            ["When Grandpa was living in New York, he volunteered at a boys’ club."],
            ["He noticed that many of the boys would come in hungry, and when you're hungry, it's hard to do your best."],
            ["So Grandpa had an idea—what if he made them a special shake to 'pep' them up?"],
            ["He wanted it to be filling, tasty, and full of energy."],
            ["So he mixed up a few ingredients: Smacks cereal, a banana, some malted milk powder, and a little honey."],
            ["Voilà! Pep!"],
            ["When he gave it to the hungry boys, they loved it! His Pep Shake was a hit."],
            ["Years later, when we were little, Grandpa started making his Pep Shakes at night."],
            ["But he always did it after we went to bed!"],
            ["The problem? It’s really hard to sleep when you hear the sound of a blender!"],
            ["One of us would always wake up and ask, 'What are you doing?'"],
            ["'I’m making Pep. Do you want to try some?' Grandpa would say with a grin."],
            ["After that, we all wanted some!"],
            ["But Grandpa wanted it to be a special treat."],
            ["So we had to take turns drinking the Pep each night."],
            ["If it was your turn, you even got to have the bottom of the shake, where all the best flavor settled!"],
            ["When he made it at night, he even warmed up the milk just a little."],
            ["Daddy loved it so much that when he grew up, he started making it for himself."],
            ["And now, he shares it with his own kids!"],
            ["Grandpa’s Pep Shake became a Fondeur family tradition."]
        ],        
        bg_color: "#2a57ad",
        svg_variant: "1",
    },
    {
        title: "Grandpa at the Drive-Thru",
        content: [
            ["Grandpa loved to act silly and do silly things."],
            ["Especially when we were ordering food at a drive-thru..."],
            ["Sometimes, when we went to order food, Grandpa would do a funny voice."],
            ["He would pretend the microphone was broken!"],
            ["A normal person would say, 'I would like to order a burger and some fries…'"],
            ["But Grandpa would say… 'I… wu… la… burger… fries…'"],
            ["The poor person taking the order would say, 'I’m sorry, sir, I can’t hear you.'"],
            ["But Grandpa was just being silly!"],
            ["Then he would say, 'Sorry, I think there was something wrong with the microphone,' and say it the right way."],
            ["But sometimes, he would keep the silly voice going for a loooong time."],
            ["After they took our order, Grandpa would sometimes embarrass Daddy."],
            ["If there was a lady working at the window (especially if Grandpa didn’t think she was pretty), he would say..."],
            ["'How are you today? I just have to say, my son thinks you're beautiful.'"],
            ["And Daddy would get sooooo embarrassed!"],
            ["But the ladies would smile and feel so special."],
            ["Sometimes, they even gave me free toys or extra fries with my meal!"],
            ["So maybe that was Grandpa’s plan…"],
            ["Or maybe… he was just being silly!"]
        ],        
        bg_color: "#ffe14d",
        svg_variant: "1",
    },
    {
        title: "Grandpa Helps a Little Girl",
        content: [
            ["One day, Daddy and Grandpa were driving through a neighborhood in Florida."],
            ["We saw a brother and sister playing outside in the street."],
            ["Suddenly, the little girl fell off her bike!"],
            ["Her older brother didn’t do anything, and it looked like she was hurt pretty bad."],
            ["So Grandpa got out of the car, picked her up, and took her to the door of her house."],
            ["Her mommy was so happy that Grandpa helped her!"],
            ["But Grandpa was upset."],
            ["He didn’t say anything to her brother, but he told me, 'His sister was hurt, and he was just looking at her.'"],
            ["I think the boy got in trouble with his mommy."],
            ["But Daddy learned a lesson that day too—"],
            ["You have to get help when people are in trouble."],
            ["When Daddy was a little older, he went to a school called St. Monica."],
            ["One day, he met a little girl in his class."],
            ["She told him that she once fell in the street, and a nice man picked her up and took her to her mom."],
            ["She was the little girl!"],
            ["Daddy told her, 'That was my dad!'"],
            ["She was so happy to meet me and grateful for Grandpa’s help."]
        ],
        bg_color: "#f8709e",
        svg_variant: "1",
    },
    {
        title: "Did You Know He Was a Genius?",
        content: [
            ["Grandpa knew so many things."],
            ["He knew about planes, he knew about electricity, he knew about plumbing, he knew about cars, he knew about outer space..."],
            ["And he would never miss the chance to tell you how much he knew."],
            ["He was very confident."],
            ["He would always tell Daddy, 'You have a dad, I had to learn by myself.'"],
            ["So Grandpa learned as much as he could."],
            ["Sometimes, Grandpa would do things that would surprise people."],
            ["Grandpa would know how to measure something perfectly, and I would ask, 'How did you do that?'"],
            ["And Grandpa would say, 'Did you know I was a genius??'"],
            ["He would get to a place without using a map because he could see it in his mind."],
            ["And I would say, 'How did you know where it was?'"],
            ["And he would say, 'Did you know I was a genius?'"],
            ["He would install very fancy equipment for television stations."],
            ["And I would say, 'When did you learn how to do that?'"],
            ["And of course, Grandpa would say... 'Did you know I was a genius?'"],
            ["He was good at math."],
            ["Before losing his hand, he said he could write with both hands."],
            ["He taught himself how to speak Portuguese (and a little Italian and French)."],
            ["He knew how to fly a plane."],
            ["He was good at drawing and he had the best handwriting I've ever seen."],
            ["He was a great singer, and he played guitar and the harmonica."],
            ["He even wrote his own songs!"],
            ["And there are so many more things!!!"],
            ["You might be asking yourself..."],
            ["How did Grandpa know all of these things??"],
            ["Well......."],
            ["Did you know he was a genius??"]
        ],
        bg_color: "#93dae4",
        svg_variant: "1",
    },
    {
        title: "Grandpa's Special Whistle",
        content: [
            ["Grandpa had a very special way of whistling."],
            ["Because Grandpa was a singer, he knew how to sing with his full voice, or as he would say, 'I sing from my diaphragm.'"],
            ["Maybe that's why he had such a unique whistle."],
            ["When Grandpa would whistle, you could hear it from miles away."],
            ["This was very helpful."],
            ["If we were in a store and Grandpa couldn't find us, he wouldn't worry."],
            ["He would just do his famous Grandpa whistle, 'Wheeeee Wheeeooooo!'"],
            ["If we were at a park and ran off, and Grandpa needed us to come back, he would whistle for that too!"],
            ["'Wheee Wheeeooo!'"],
            ["In a theme park, at church, in a restaurant—wherever we were, if we heard Grandpa's whistle, we knew exactly where to find him."],
            ["And he always knew how to find us."],
            ["Just follow the sound of the whistle!"],
            ["'Wheeee Wheeeoooo!'"]
        ],
        bg_color: "#01b4c9",
        svg_variant: "1",
    },
    {
        title: "Grandpa Flies a Plain",
        content: [
            ["Grandpa loved planes."],
            ["He liked them so much that he would go to a small airport to take practice flights."],
            ["Whenever Grandpa did a practice flight, he had a flight instructor with him to keep things safe."],
            ["But Grandpa knew a lot about planes, so he didn’t need much help."],
            ["He loved flying so much that he would sometimes take other people to sit in the back seat with him!"],
            ["One time, he even took Titi Monica to fly on her birthday!"],
            ["One day, he asked Daddy if he wanted to go flying with him."],
            ["Daddy is a little scared of heights, but he trusted Grandpa."],
            ["So they went to a small airport called Perry Airport, met with the flight instructor, and got into a little plane called a Cessna."],
            ["Everything was going fine. In a small plane, you can feel everything."],
            ["Then Grandpa told the flight instructor, 'I want to go this way...'", "And he took the plane over a large body of water."],
            ["This made Daddy a little bit nervous, but the water looked nice."],
            ["I just told Grandpa, 'That’s a lot of water!'"],
            ["Then, as they were getting close to land again, there was a big crane right in front of the plane!"],
            ["Grandpa asked the flight instructor, 'Can we do a touch and go?'"],
            ["Daddy had no idea what he was talking about."],
            ["But the flight instructor said, 'Sure!'"],
            ["And just like that, they flew under the crane, touched the ground for just a second, then took off again!"],
            ["It was very exciting—and a little scary."],
            ["Grandpa wasn’t nervous at all."],
            ["Daddy was very proud of him... but he would rather stay on the ground!"]
        ],
        bg_color: "#d8ba66",
        svg_variant: "1",
    },
    {
        title: "Walk This Way!",
        content: [
            ["Grandpa loved doing silly things."],
            ["Sometimes, when we were in a store or in front of a lot of people, Grandpa would tell us to 'Walk this way!'"],
            ["Now, we knew that it was just another way of saying 'Follow me!'"],
            ["But to Grandpa, it was the perfect excuse to be silly!"],
            ["When Grandpa said 'Walk this way!' he would stretch out his legs from side to side as he walked and make a silly face!"],
            ["It was so embarrassing because everyone would look at him, but it was also really funny!"],
            ["We never copied him, but we always laughed."],
            ["Sometimes, when Grandpa got out of the shower or put on his pajamas, he would pull his pants way up over his belly!"],
            ["And then he would do his funny walk around the house, pretending like everything was normal."],
            ["It made us laugh so much!"],
            ["Can you pull your pants over your belly and do a funny walk like Grandpa?"],
            ["Don't forget to say, 'Walk this way!'"]
        ],        
        bg_color: "#9d87f5",
        svg_variant: "1",
    },
    {
        title: "Grandpa the Food Tester",
        content: [
            ["Coming Soon"]
        ],
        bg_color: "#6bb4fd",
        svg_variant: "1",
    },
    {
        title: "Grandpa Climbs a Scaffold",
        content: [
            ["Coming Soon"]
        ],
        bg_color: "#8053fa",
        svg_variant: "1",
    },
    {
        title: "Grandpa the World Traveler",
        content: [
            ["Coming Soon"]
        ],
        bg_color: "#01b4c9",
        svg_variant: "1",
    },
    {
        title: "Grandpa the Builder",
        content: [
            ["Coming Soon"]
        ],
        bg_color: "#ef6c01",
        svg_variant: "1",
    },
    {
        title: "Grandpas Little Treasures",
        content: [
            ["Coming Soon"]
        ],
        bg_color: "#d92626",
        svg_variant: "1",
    }
]